on:
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger custom event
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/{owner}/{repo}/dispatches" \
            -d '{"event_type": "custom_pull_request_event", "client_payload": {"pr_number": "${{ github.event.pull_request.number }}"} }'
