name: "PR Event Listener"

on:
  pull_request:
    types: [opened, edited, synchronize, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  concurrency:
    group: ${{ github.workflow }}-${{ github.run_id }}
    cancel-in-progress: true

jobs:
  trigger-pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          echo "PR_TITLE=<<>>" >> $GITHUB_ENV
          echo "PR_NUMBER=<<>>" >> $GITHUB_ENV

      - name: Extract PR Information for Pull Request Event
        if: github.event_name == 'pull_request'
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Extract PR Information for Pull Request Review Event
        if: github.event_name == 'pull_request_review'
        run: |
          echo "PR_TITLE=${{ github.event.pull_request_review.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request_review.pull_request.number }}" >> $GITHUB_ENV

      - name: Trigger Second Workflow
        run: |
          curl -X POST \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               --data '{"event_type": "trigger-second-workflow", "client_payload": {"pr_title": "'"$PR_TITLE"'", "pr_number": "'"$PR_NUMBER"'"}}'
