name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  add-reviewer:
    permissions: write-all
    name: Add Reviewer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script to add reviewer
      env:
        GITHUB_TOKEN: ${{ secrets.THIS_REPO_SECRET }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_REVIEWERS: ${{ toJson(github.event.pull_request.requested_reviewers) }}
        PATTERN: "^\\w+!:"
        REVIEWER: "torres-sdk"
      run: bash .github/scripts/add-reviewer.sh
