name: "Lint PR"

on:
  pull_request:
    types: [opened, edited, synchronize, review_requested, review_request_removed]

  repository_dispatch:
    types: [custom_pull_request_event]

env:
  GITHUB_TOKEN: ${{ secrets.THIS_REPO_SECRET }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_TITLE: ${{ github.event.pull_request.title }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-reviewers:
    name: ${{ github.event_name }} - Get Reviewers
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
        WAS_REVIEWED_BY_FE: ${{ steps.reviewers.outputs.WAS_REVIEWED_BY_FE }}
        HAS_FE_REVIEW_REQUEST: ${{ steps.reviewers.outputs.HAS_FE_REVIEW_REQUEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Requested Reviewers
        id: reviewers
        run: |
          FE_MEMBERS=$(gh api orgs/test-org-torres/teams/torres-sdk/members --jq '.[].login')
          PR_DATA=$(gh pr view https://github.com/test-org-torres/test-ci/pull/$PR_NUMBER --json reviewRequests,reviews)
          HAS_FE_REVIEW_REQUEST=$(echo "$PR_DATA" | jq '[.reviewRequests[].slug | select(. == "test-org-torres/torres-sdk")] | length > 0')
          REVIWERS=$(echo "$PR_DATA" | jq -r '.reviews[].author.login')

          echo "FE_MEMBERS: $FE_MEMBERS"
          echo "HAS_FE_REVIEW_REQUEST: $HAS_FE_REVIEW_REQUEST"
          echo "PR_DATA: $PR_DATA"
          echo "REVIWERS: $REVIWERS"

          WAS_REVIEWED_BY_FE="false"
          for member in $FE_MEMBERS; do
            echo "member: $member"
            for reviewer in $REVIWERS; do
              echo "reviewer: $reviewer"
              if [ "$member" == "$reviewer" ]; then
                echo "entered inner" 
                WAS_REVIEWED_BY_FE="true"
                break 2
              fi
            done
          done

        
           echo "WAS_REVIEWED_BY_FE: $WAS_REVIEWED_BY_FE"  
          echo "WAS_REVIEWED_BY_FE=$WAS_REVIEWED_BY_FE" >> $GITHUB_OUTPUT
          echo "HAS_FE_REVIEW_REQUEST=$HAS_FE_REVIEW_REQUEST" >> $GITHUB_OUTPUT

  add-reviewer:
    permissions: write-all
    name: Add Reviewer
    needs: [get-reviewers]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run script to add reviewer
      env:
        PR_REVIEWERS: ${{ toJson(github.event.pull_request.requested_reviewers) }}
        PR_TEAM_REVIEWERS: ${{ toJson(github.event.pull_request.team_reviewers) }}
        PATTERN: "^\\w+!:"
        WAS_REVIEWED_BY_FE: ${{needs.get-reviewers.outputs.WAS_REVIEWED_BY_FE}}
        HAS_FE_REVIEW_REQUEST: ${{needs.get-reviewers.outputs.HAS_FE_REVIEW_REQUEST}}
        REVIEWER: "test-org-torres/torres-sdk"

      run: bash .github/scripts/add-reviewer.sh

  validate-fe-review:
    permissions: write-all
    name: Validate FE Review
    needs: [get-reviewers, add-reviewer]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure FE Approval
      env:
        HAS_FE_REVIEW_REQUEST: ${{needs.get-reviewers.outputs.HAS_FE_REVIEW_REQUEST}}

      run: |
        if [ "$HAS_FE_REVIEW_REQUEST" == "true" ]; then
          exit 1
        fi
