name: "Validate PR"

on:
  workflow_run:
      workflows: ["Lint PR"]
      types:
        - completed

        
  pull_request_review:
    types: [submitted, edited, dismissed]


jobs:
  validate-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.THIS_REPO_SECRET }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      EVENT: ${{ github.event }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Requested Reviewers
        id: reviewers
        run: |
          echo "EVENT=$EVENT"
          PR_DATA=$(gh pr view https://github.com/test-org-torres/test-ci/pull/$PR_NUMBER --json reviewRequests,reviews)
          HAS_FE_REVIEW_REQUEST=$(echo "$PR_DATA" | jq '[.reviewRequests[].slug | select(. == "test-org-torres/torres-sdk")] | length > 0')

          if [ "$IS_APPROVED_BY_FE" == "true" ]; then
            exit 1
          fi
